services:
  carhubconnect_backend:
    container_name: carhubconnect_backend
    build: .
    ports:
      - 5020:5020
    environment:
      - MONGO_URI=mongodb://mongodb:27017/carhub_db
    depends_on:
      - mongodb
  mongodb:
    container_name: carhubconnect_db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: